# Generated by Django 5.1 on 2024-08-17 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_userform_email_alter_userform_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
