# Generated by Django 5.1 on 2024-09-08 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_userform_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_id', models.CharField(max_length=255)),
                ('coin', models.CharField(max_length=50)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('balance', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.userform')),
            ],
        ),
    ]
